"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@#)0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',  # Django Channels - must be before django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',  # Django Channels
    'app.admin_api',
    'app.secondhand_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'secondhand_platform',  # 假设数据库名为 secondhand_db，需要确认
        'USER': 'root',           # 假设用户名为 root，需要确认
        'PASSWORD': '123456',   # 假设密码为 password，需要确认
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False  # 使用本地时间，方便存储和显示


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # Default to allow any, secure specific views
    ),
    'DEFAULT_PAGINATION_CLASS': 'app.secondhand_app.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
}

# Admin JWT Settings
ADMIN_JWT_SECRET = 'admin-secret-key-change-in-production'
ADMIN_JWT_EXPIRE_DAYS = 1

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Token有效期1天
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh Token有效期7天
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for development
CORS_ALLOW_CREDENTIALS = True

# Channel Layers (Redis configuration for WebSocket)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# User model
AUTH_USER_MODEL = 'auth.User'

# Price API Settings
# 优先顺序: CUSTOM > JUHE > RAPIDAPI > BAIDU > ALIYUN > APISPACE > SCRAPER
PRICE_API_PROVIDER = 'SCRAPER'  # 默认使用爬取服务

# 自定义API配置（最高优先级）
CUSTOM_PRICE_API_URL = ''
CUSTOM_PRICE_API_KEY = ''
CUSTOM_PRICE_API_HEADER_KEY = 'Authorization'  # Header中的Key名称
CUSTOM_PRICE_API_HEADER_PREFIX = 'Bearer '     # Header中的Value前缀
CUSTOM_PRICE_API_PARAM_KEY = 'token'           # Query参数中的Key名称
CUSTOM_PRICE_API_METHOD = 'POST'  # 请求方法: 'GET' 或 'POST'
CUSTOM_PRICE_API_AUTH_TYPE = 'bearer'  # 认证类型: 'bearer', 'header', 'query'

# ==================== 公开API服务配置 ====================
# 启用公开API服务（推荐使用）
ENABLE_PUBLIC_API = False  # 是否启用公开API服务

# 聚合数据API配置（推荐）
# 注册地址：https://www.juhe.cn
JUHE_API_KEY = ''  # 聚合数据API密钥
JUHE_PRICE_API_URL = ''  # 价格查询API地址（需要根据实际API文档配置）

# RapidAPI配置
# 注册地址：https://rapidapi.com
RAPIDAPI_KEY = ''  # RapidAPI密钥
RAPIDAPI_HOST = ''  # API Host
RAPIDAPI_PRICE_API_URL = ''  # 价格查询API地址

# 百度API配置
BAIDU_API_KEY = ''  # 百度API密钥
BAIDU_PRICE_API_URL = ''  # 价格查询API地址

# 阿里云API配置
ALIYUN_API_KEY = ''  # 阿里云API密钥
ALIYUN_API_SECRET = ''  # 阿里云API密钥
ALIYUN_PRICE_API_URL = ''  # 价格查询API地址

# API Store配置
APISPACE_API_KEY = ''  # API Store密钥
APISPACE_PRICE_API_URL = ''  # 价格查询API地址

# ⚠️ 爬取服务配置（仅供学习研究，不推荐用于生产环境）
# 警告：爬取第三方平台可能违反服务条款和法律，请谨慎使用
ENABLE_PRICE_SCRAPER = False  # 是否启用爬取服务

# 手动配置的API端点（如果找到了实际的API地址，可以在这里配置）
SCRAPER_API_URL = ''  # 例如: 'https://www.aihuishou.com/api/v1/estimate'
SCRAPER_API_METHOD = 'POST'  # GET 或 POST
SCRAPER_API_KEY = ''  # API密钥（如果需要）
SCRAPER_API_SECRET = ''  # API密钥（如果需要）

# ========== 支付宝沙箱支付配置 ==========
# 文档：https://opendocs.alipay.com/common/02kkv7
# 沙箱应用管理：https://openhome.alipay.com/develop/sandbox/app
# 沙箱账号管理：https://openhome.alipay.com/develop/sandbox/account

# 支付宝沙箱网关地址
ALIPAY_SANDBOX_GATEWAY_URL = 'https://openapi-sandbox.dl.alipaydev.com/gateway.do'

# 应用配置（从支付宝开放平台沙箱控制台获取）
# 获取方式：
# 1. 登录 https://openhome.alipay.com/develop/sandbox/app
# 2. 选择或创建沙箱应用
# 3. 在应用详情页获取 APPID
ALIPAY_SANDBOX_APP_ID = '9021000158624650'  # APPID（必填，从控制台获取）

# 应用私钥（必填，RSA2格式，2048位）
# 获取方式：
# 1. 使用支付宝密钥生成工具或 OpenSSL 生成密钥对
# 2. 从生成的私钥文件中获取（可以是完整格式或仅Base64字符串）
# 3. 注意：这是您自己生成的私钥，请妥善保管，不要泄露
ALIPAY_SANDBOX_APP_PRIVATE_KEY = 'MIIEpQIBAAKCAQEAsIBLYDDaOOzNx5WO/CtdKJA9O7An3ghw3PlqHU/+YhN4MmN1QZhtxheX/FfxWZ2jQ2KzxcJkrnQ9pix/Alil7gGeeawRGX+0B/WWsvmNk/LT01bICSMnym8P80J4Q29exh+yXS/b5pEAo7W63tp9rjzZ63O1aKwqydcL1gagoUNDgIOC0i75BOwtiFm9QPNtySDmuN9OMw+aWJnpYGjejQ0Tbj7uv9ctitzS45lH1ayxxa/oyrqsVpzGHFU9ZnplcNwrS11fId0ECFEPZN4utBnw3j5ZBjuRxhV6DTL/E2X2WGTXMkdZnpKY3pI/u6y5A2mQTy8rzjiawIwU6G6k/wIDAQABAoIBAG54bjUPfpZgiM+hqTPmBFHOLbU9JUbQK6vzI9qi5coG+5U2MP7UY+i3fbZAaNw5USVtEq31ZMTYFnn6oagbSge01ba73pwCFPFiYmc00MtIEhLV3y/w5AfNCcOs188FVuFUl3PB77XZDfhpV0QCpuU2SwMWkfWoxMM+KLdVwJYNkj89ov0RtxGnJ7d0lTaAYO3D/RmeJY0bWo8mXFd+BVJML+MTO1Bt4dqwUEghaehglKnsJUXNcV0vidztIfVerWvBUl0fbT48LKfyK0y9S5KVsDKPxAxpkO1hf0D2W2jditcGFKuGXGVzEXiQqIi7aDquIdAad7pwZV9Uvdkf7ekCgYEA8mq1/6/cyVFK7/k69mndFWryVbUzTh2CbL/xRqo8HP7jShxWAJ+D+GtA378jVM9QVYW2FT86BLY/7LbIsAAQsviSi3K3JxTAx6ohXrsiZuXexHg0IrxmKsdJvYEaB4PbuRBi937mB+i4y3PNtQ2/Fr1sUFmB8dNgidOW2gpkas0CgYEAumQSb8BWypUg7eHskEl4BUL/H4YmsPi39lqfo6R3gX1HMvqHXK6AEO2kgaJn/oJ10TJyUgAnscOeZ4uWiE3jUsFKUQA2XYMJrpV5+0Zd3rxeJKbljgeYC3o6V4vOfzn1Eyg8HenexsYv1dHbHv6cxo1Flhi8pimAQzR0SIedpvsCgYEA8l9ZCoTVtf7uctJ4bmjYIBLmqmTaIA8HGR4r6SBJrB/4Nl/waP0UIKtzmIHtnF0PEAL5U3L82jsx3MXAD6BxEc/QDVar4oowWTEz3hgyRDkuqrcYQWamq7zHcI6E7OCcLgNBP/0DlwLKyLhHAu/0j5Limc90Scmyqvr/x48+aT0CgYEAlYPO0jvsoybLOmc/V2LH1xiuBECdatqo3wJFCoTUpFe1NGyJBsynyGyIyMBZQWyvS7d2wtaDAPLVb2QmxYINNwX8MkvEUHDb5GLdbbY9eH2L20TR4YOv8I0EndN1OtNoBw0AZFKFNNgn6RIk/pDpe9A5ILUJJxUlYUODf+bhjN8CgYEAwAV2cWAgSeqfsnM8vyawQsGd42mn9pQ4hbVf0DFnNqUyL+i/Qc8n8dv9/M3n2nYH/dpoR7XtochC8stxtQTztLj6wyN+YJJ5vd/7pVWJHFSB8qCgaVGkOCUyYT7q0zR4wGfGRQiW9Seg/01AjhTbibtfGvYOtUkg4PJGBCWzstw='  # 应用私钥（必填，RSA2格式）

# 支付宝公钥（必填，从沙箱控制台获取）
# 获取方式：
# 1. 在沙箱应用详情页，点击"接口加签方式" -> "设置"
# 2. 上传应用公钥后，支付宝会返回"支付宝公钥"
# 3. 复制这个公钥配置到这里
# 注意：这是支付宝提供的公钥，用于验证支付宝返回的数据签名
ALIPAY_SANDBOX_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjvYXLvwQOhTEtpuDEGJB5+TFhqgAObVy9LD4qfi60xS78kl8EkWg3AMq4n5mwwIvkExF3sByHKJQ5M12RsnUFCxaQUwdiGpPeFk9nkB6BZoDyegj68Na5HnC50kvwO5C9f+dKEBsTGaUsrXjBWlGqj6g+XnCeUffY9Xi9XHIwn/lXC0uekoXYR1qU5/QKLGuwXiPuBQVvyRVZBEUO7rZWPbhvbG48WWmgytdMeTIYdvPnjI7u5oEITTwCwCL2h8swQu3W7sxBEz9vA/G3IpYbZbuutVTjrnP/vWuY9nc0wwutPGEn6xWiZ2raj/pJ5kgOPSSkqIIBDE2Q0yssbMzTwIDAQAB'  # 支付宝公钥（必填，从沙箱控制台获取）

# 回调地址配置
# 注意：
# - 本地开发：可以使用 http://127.0.0.1:8000 或 http://localhost:8000
# - 生产环境：必须使用 HTTPS 和公网可访问的地址
# - 需要在支付宝开放平台配置回调地址白名单（生产环境）
ALIPAY_SANDBOX_NOTIFY_URL = 'http://127.0.0.1:8000/api/payment/alipay/notify/'  # 异步通知地址（本地测试用，生产环境需改为公网地址）
ALIPAY_SANDBOX_RETURN_URL = 'http://localhost:5173/order/'  # 支付完成跳转地址（本地测试用）

# 前后端URL配置（用于动态构建回调地址）
# 这些配置会在创建支付订单时动态构建回调地址
FRONTEND_URL = 'http://localhost:5173'  # 前端地址
BACKEND_URL = 'http://127.0.0.1:8000'  # 后端地址

# 演示模式（可选）
# 注意：支付宝沙箱环境本身就是测试环境，此选项主要用于本地调试
# 当设置为 True 时，某些接口可能跳过真实调用（如果实现了演示逻辑）
ALIPAY_SANDBOX_DEMO_MODE = False  # True=演示模式, False=真实支付

# ========== 日志配置 ==========
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'app.secondhand_app': {  # 应用日志
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
