"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@#)0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0=0'

# Customer service user used by admin chat
SUPPORT_SERVICE_USERNAME = os.getenv('SUPPORT_SERVICE_USERNAME', 'support_service')
SUPPORT_SERVICE_EMAIL = os.getenv('SUPPORT_SERVICE_EMAIL', 'support@example.com')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',  # Django Channels - must be before django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',  # Django Channels
    'app.admin_api',
    'app.secondhand_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'secondhand_platform',  # 假设数据库名为 secondhand_db，需要确认
        'USER': 'root',           # 假设用户名为 root，需要确认
        'PASSWORD': '123456',   # 假设密码为 password，需要确认
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False  # 使用本地时间，方便存储和显示


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # Default to allow any, secure specific views
    ),
    'DEFAULT_PAGINATION_CLASS': 'app.secondhand_app.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
}

# Admin JWT Settings
ADMIN_JWT_SECRET = 'admin-secret-key-change-in-production'
ADMIN_JWT_EXPIRE_DAYS = 1

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Token有效期1天
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh Token有效期7天
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for development
CORS_ALLOW_CREDENTIALS = True

# Security headers / cookies (disabled for local development)
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Channel Layers (Redis configuration for WebSocket)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# User model
AUTH_USER_MODEL = 'auth.User'

# Price API Settings
# 优先顺序: CUSTOM > JUHE > RAPIDAPI > BAIDU > ALIYUN > APISPACE > SCRAPER
PRICE_API_PROVIDER = 'SCRAPER'  # 默认使用爬取服务

# 自定义API配置（最高优先级）
CUSTOM_PRICE_API_URL = ''
CUSTOM_PRICE_API_KEY = ''
CUSTOM_PRICE_API_HEADER_KEY = 'Authorization'  # Header中的Key名称
CUSTOM_PRICE_API_HEADER_PREFIX = 'Bearer '     # Header中的Value前缀
CUSTOM_PRICE_API_PARAM_KEY = 'token'           # Query参数中的Key名称
CUSTOM_PRICE_API_METHOD = 'POST'  # 请求方法: 'GET' 或 'POST'
CUSTOM_PRICE_API_AUTH_TYPE = 'bearer'  # 认证类型: 'bearer', 'header', 'query'

# ==================== 公开API服务配置 ====================
# 启用公开API服务（推荐使用）
ENABLE_PUBLIC_API = False  # 是否启用公开API服务

# 聚合数据API配置（推荐）
# 注册地址：https://www.juhe.cn
JUHE_API_KEY = ''  # 聚合数据API密钥
JUHE_PRICE_API_URL = ''  # 价格查询API地址（需要根据实际API文档配置）

# RapidAPI配置
# 注册地址：https://rapidapi.com
RAPIDAPI_KEY = ''  # RapidAPI密钥
RAPIDAPI_HOST = ''  # API Host
RAPIDAPI_PRICE_API_URL = ''  # 价格查询API地址

# 百度API配置
BAIDU_API_KEY = ''  # 百度API密钥
BAIDU_PRICE_API_URL = ''  # 价格查询API地址

# 高德IP定位配置
AMAP_API_KEY = 'f02f4bf9cffe783a1318a91646bd6d45'

AMAP_IP_API_URL = 'https://restapi.amap.com/v3/ip'
AMAP_DISTRICT_API_URL = 'https://restapi.amap.com/v3/config/district'

# 阿里云API配置
ALIYUN_API_KEY = ''  # 阿里云API密钥
ALIYUN_API_SECRET = ''  # 阿里云API密钥
ALIYUN_PRICE_API_URL = ''  # 价格查询API地址

# API Store配置
APISPACE_API_KEY = ''  # API Store密钥
APISPACE_PRICE_API_URL = ''  # 价格查询API地址

# ⚠️ 爬取服务配置（仅供学习研究，不推荐用于生产环境）
# 警告：爬取第三方平台可能违反服务条款和法律，请谨慎使用
ENABLE_PRICE_SCRAPER = False  # 是否启用爬取服务

# 手动配置的API端点（如果找到了实际的API地址，可以在这里配置）
SCRAPER_API_URL = ''  # 例如: 'https://www.aihuishou.com/api/v1/estimate'
SCRAPER_API_METHOD = 'POST'  # GET 或 POST
SCRAPER_API_KEY = ''  # API密钥（如果需要）
SCRAPER_API_SECRET = ''  # API密钥（如果需要）

# ========== 支付宝支付配置 ==========
# 文档：https://opendocs.alipay.com/common/02kkv7
# 应用管理：https://open.alipay.com/

# 支付宝网关地址
# 生产环境：https://openapi.alipay.com/gateway.do
# 沙箱环境（测试用）：https://openapi-sandbox.dl.alipaydev.com/gateway.do
# 注意：本地测试时使用沙箱环境，上线前需要改为生产环境地址
ALIPAY_GATEWAY_URL = 'https://openapi-sandbox.dl.alipaydev.com/gateway.do'  # 本地测试使用沙箱环境

# 应用配置（从支付宝开放平台控制台获取）
# 获取方式：
# 1. 登录 https://open.alipay.com/
# 2. 进入控制台 -> 网页&移动应用
# 3. 创建应用或选择已有应用
# 4. 在应用详情页获取 APPID
ALIPAY_APP_ID = '9021000158624650'  # APPID（必填，从控制台获取）

# 应用私钥（必填，RSA2格式，2048位）
# 获取方式：
# 1. 使用支付宝密钥生成工具或 OpenSSL 生成密钥对
# 2. 从生成的私钥文件中获取（可以是完整格式或仅Base64字符串）
# 3. 注意：这是您自己生成的私钥，请妥善保管，不要泄露
ALIPAY_APP_PRIVATE_KEY = 'MIIEowIBAAKCAQEApdiTemjXz2N105BvALkPBuHrp2dJwNJnO9SqtGGfXq+Lvu8rymPALmrACQcBi7zS2eBm1h28rJRRePeS9saaBtsuayZkDNIrlMRjhien4sXce/xIjRuwGuPEcIfUxIzkwuva1Rata4PD710ty5QhNbnGDmB02Fo7xaazdSJi8K/KySoKQ4ktIKnu4Ff2hSSJuoFmWtNBJ7dcXksK9+SCpYL2KGf6eUMHleDd4zbgsRSgj+khwWjqwmyhcySbLYs9MWrZpAwA11sy8GMTRZ+ulpdr0Mb99bxXxzOYtVqlOrM/rZ6wIV2qK2131dnICiVd/PLJT5YBDTAWdb/+U3y8VQIDAQABAoIBACIInNMs+sSja4WcCTuDvpKyABMdfiQkyWycyt8zfWoH6kyndjwVVlXwMDJqDqYnfLmbdF8SQSrFUSba33zm6qrnhdIVUcjTxH/GAYqBTtGZuxJyhkz21p/eB+zz4vTm2PcrQYAjJDmBE89mNsSlRF9rHTrMDo5rjgKUoBU0lks/4avqj8F0Miq7hJRoJJdCbHVhC0o2XTl5xSJBMgViS6nT/4mjKS6+sLlqE9C9fKEJHlZDcKJFLlJJO5gwbJ0HTM3Fp2ZnFchBkFIhV72I5GpR/weYoqaE02M6wDjOEKhnccSdy7CbUNHCwGJ5Rl+4bo+T6+Fob/i+amBY7HubtC0CgYEA/NZy34DYUqSRkmOeQmpuz88wOJt1maVbRcR5YfF+pXwWklBIoR98rgQ+CniMSgxdYoyuEF2BTqrkf1GELMPBNgBKQaFN7d9kYe95ManBfbgN/WcXgjhXAT8kGQKT7hlL/U+JSOmTHSE0rz3twDPNAyNsH823Zpkz3BqGJdfQYJcCgYEAp+uXjm1DZCCU3MifappgYRZTi5qFWk6MAal6eayauQzgpeb01Bu+GU4fhNgccrIVRHVKvE9U4K9JSE6pr547XWsjC8ecZdvmb3mGY3Kz1tlte0AGRxYgmti6SkaiN3lEMZi9BLlN6+iE65gjSrAWt6Agb6dwNn9cWg3OMAiL+/MCgYAEMJGKvpnXFL8My/XNZ/IaI3bLGVhjiWfvygew5c2RdHLzTb1GXj00rQFSLxk0COxrO6WOw93mrdJHgdRM4ZmMCYkxeTjPXkpNjShW+FcqfChPMKwlDkXy0VcJyw8kfOrTccP2n1g+vVQgK0iLTNBy4t1h0YjefF9toErkyaS8VQKBgQCVzDWHeTGFQQuLae3My6ru8VvWTiJoTWnYkbgQk0nziuldFouSLK2JJYg4mhHGv9b5Gylwk9TEG5rkRkhZwm5zCABbodaDh4gqKd8ZGFoWcCCasqLnB3ZOrMiDOj+7/RI4rGjyrdw1d1gcU7woBK4/YTmOYXBZLYTVUTt+3iECwQKBgG5wzFSx8uFu64uWNVh43GHPXa0CQYihrm8n3Xzi5A+EPPOUgJ2G63cCAagmMz7zCzTXwbVZAbNFWuA1RAak75s6wLwrbpOCTErGglRRRY4fxxY79BYANL7aGKI1Ejgy4yop/TFKOUHiSw2AZLyVeoSBuqdrj//FJ+Va+fq2wyps'  # 应用私钥（必填，RSA2格式）

# 支付宝公钥（必填，从控制台获取）
# 获取方式：
# 1. 在应用详情页，点击"接口加签方式" -> "设置"
# 2. 上传应用公钥后，支付宝会返回"支付宝公钥"
# 3. 复制这个公钥配置到这里
# 注意：这是支付宝提供的公钥，用于验证支付宝返回的数据签名
ALIPAY_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjvYXLvwQOhTEtpuDEGJB5+TFhqgAObVy9LD4qfi60xS78kl8EkWg3AMq4n5mwwIvkExF3sByHKJQ5M12RsnUFCxaQUwdiGpPeFk9nkB6BZoDyegj68Na5HnC50kvwO5C9f+dKEBsTGaUsrXjBWlGqj6g+XnCeUffY9Xi9XHIwn/lXC0uekoXYR1qU5/QKLGuwXiPuBQVvyRVZBEUO7rZWPbhvbG48WWmgytdMeTIYdvPnjI7u5oEITTwCwCL2h8swQu3W7sxBEz9vA/G3IpYbZbuutVTjrnP/vWuY9nc0wwutPGEn6xWiZ2raj/pJ5kgOPSSkqIIBDE2Q0yssbMzTwIDAQAB'  # 支付宝公钥（必填，从控制台获取，已更新）

# 前后端URL配置（用于动态构建回调地址）
# 注意：
# 1. 如果只启动了后端 ngrok 隧道（8000端口），前端应该使用 localhost
# 2. 如果前后端都启动了 ngrok 隧道，则分别配置对应的地址
# 3. 当前代码会自动检测 ngrok：
#    - 如果前端是 ngrok 地址，直接跳转到前端（最佳体验）
#    - 如果前端是 localhost 但后端是 ngrok，使用后端重定向页面

# 前端地址配置
# 使用前端 ngrok 地址
# 前端地址（现在使用本地地址）
FRONTEND_URL = 'http://localhost:5173'  # 本地前端地址
# 如果使用 ngrok 前端隧道，取消下面的注释并注释掉上面的行：
# FRONTEND_URL = 'https://georgianna-presanitary-clair.ngrok-free.dev'  # 前端 ngrok 地址

# 后端地址（使用 ngrok 内网穿透地址，用于支付回调）
BACKEND_URL = 'https://hypochondriacally-nondiscretionary-kylie.ngrok-free.dev'  # 后端 ngrok 地址
# 注意：每次重启 ngrok，地址可能会变化，需要更新此配置
# 本地地址（不使用 ngrok 时）：
# BACKEND_URL = 'http://127.0.0.1:8000'

# 回调地址配置（会在代码中动态构建）
# 注意：
# - 本地开发：可以使用 http://127.0.0.1:8000 或 http://localhost:8000
# - 生产环境：必须使用 HTTPS 和公网可访问的地址
# - 需要在支付宝开放平台配置回调地址白名单（生产环境）

# ========== 日志配置 ==========
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'app.secondhand_app': {  # 应用日志
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# ========== 分账与佣金配置 ==========
# 是否启用支付宝分账结算（沙箱可用）
ENABLE_ALIPAY_ROYALTY = True
# 平台佣金比例（示例：5%）
PLATFORM_COMMISSION_RATE = 0.05
# 买家确认收货后自动分账
SETTLE_ON_ORDER_COMPLETED = True
# 可选：平台自身登录账号（如需显式分账到平台账户）
PLATFORM_ALIPAY_LOGON_ID = ''
SETTLEMENT_FALLBACK_TO_TRANSFER = True
