# Generated by Codex to align AdminInspectionReport model with existing MySQL table.

from django.db import migrations, models


def sync_inspection_report_columns(apps, schema_editor):
    table = 'admin_api_admininspectionreport'
    if schema_editor.connection.vendor != 'mysql':
        return
    # Ensure table exists before attempting alterations (should exist after 0001).
    if table not in schema_editor.connection.introspection.table_names():
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SHOW COLUMNS FROM `{table}`")
        columns = {row[0]: row for row in cursor.fetchall()}
        alterations = []

        if 'evidence' not in columns:
            alterations.append("ADD COLUMN `evidence` JSON NOT NULL DEFAULT '[]'")

        if 'overall_result' not in columns:
            alterations.append("ADD COLUMN `overall_result` VARCHAR(32) NOT NULL DEFAULT 'passed'")
        else:
            alterations.append("MODIFY COLUMN `overall_result` VARCHAR(32) NOT NULL DEFAULT 'passed'")

        if 'recommend_price' not in columns:
            alterations.append("ADD COLUMN `recommend_price` DECIMAL(10,2) NULL")

        if 'score' not in columns:
            alterations.append("ADD COLUMN `score` DECIMAL(5,2) NULL")

        if 'template_name' not in columns:
            alterations.append("ADD COLUMN `template_name` VARCHAR(64) NOT NULL DEFAULT 'default'")
        else:
            alterations.append("MODIFY COLUMN `template_name` VARCHAR(64) NOT NULL DEFAULT 'default'")

        if 'template_version' not in columns:
            alterations.append("ADD COLUMN `template_version` VARCHAR(32) NOT NULL DEFAULT 'v1'")
        else:
            alterations.append("MODIFY COLUMN `template_version` VARCHAR(32) NOT NULL DEFAULT 'v1'")

        if alterations:
            cursor.execute(f"ALTER TABLE `{table}` " + ", ".join(alterations))


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_admintokenblacklist_adminrole_permissions_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='admininspectionreport',
                    name='evidence',
                    field=models.JSONField(default=list),
                ),
                migrations.AddField(
                    model_name='admininspectionreport',
                    name='overall_result',
                    field=models.CharField(default='passed', max_length=32),
                ),
                migrations.AddField(
                    model_name='admininspectionreport',
                    name='recommend_price',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                migrations.AddField(
                    model_name='admininspectionreport',
                    name='score',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                migrations.AddField(
                    model_name='admininspectionreport',
                    name='template_name',
                    field=models.CharField(default='default', max_length=64),
                ),
                migrations.AddField(
                    model_name='admininspectionreport',
                    name='template_version',
                    field=models.CharField(default='v1', max_length=32),
                ),
            ],
            database_operations=[
                migrations.RunPython(sync_inspection_report_columns, migrations.RunPython.noop),
            ],
        ),
    ]
