# Generated by Django 5.2.8 on 2025-12-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_sync_inspection_report_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleDeviceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(help_text='如：手机、平板、笔记本', max_length=32, verbose_name='设备类型')),
                ('brand', models.CharField(max_length=64, verbose_name='品牌')),
                ('model', models.CharField(max_length=128, verbose_name='型号')),
                ('storages', models.JSONField(default=list, help_text='如：["128GB", "256GB", "512GB"]', verbose_name='存储容量列表')),
                ('series', models.CharField(blank=True, help_text='如：iPhone 13系列', max_length=64, verbose_name='系列')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_api.adminuser', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '回收机型模板',
                'verbose_name_plural': '回收机型模板',
                'ordering': ['device_type', 'brand', 'model'],
                'unique_together': {('device_type', 'brand', 'model')},
            },
        ),
        migrations.CreateModel(
            name='RecycleQuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(help_text='从1开始', verbose_name='步骤顺序')),
                ('key', models.CharField(help_text='如：channel, color, storage', max_length=64, verbose_name='问题标识')),
                ('title', models.CharField(max_length=128, verbose_name='问题标题')),
                ('helper', models.CharField(blank=True, max_length=256, verbose_name='提示文本')),
                ('question_type', models.CharField(choices=[('single', '单选'), ('multi', '多选')], default='single', max_length=16, verbose_name='问题类型')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='admin_api.recycledevicetemplate', verbose_name='机型模板')),
            ],
            options={
                'verbose_name': '问卷步骤模板',
                'verbose_name_plural': '问卷步骤模板',
                'ordering': ['device_template', 'step_order'],
                'unique_together': {('device_template', 'key'), ('device_template', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='RecycleQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='如：official, black, 256GB', max_length=128, verbose_name='选项值')),
                ('label', models.CharField(help_text='显示给用户的文本', max_length=128, verbose_name='选项标签')),
                ('desc', models.CharField(blank=True, help_text='辅助说明文本', max_length=256, verbose_name='选项描述')),
                ('impact', models.CharField(blank=True, choices=[('positive', '正面影响'), ('minor', '轻微影响'), ('major', '重大影响'), ('critical', '严重影响')], max_length=16, verbose_name='对估价的影响')),
                ('option_order', models.IntegerField(default=0, verbose_name='选项顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='admin_api.recyclequestiontemplate', verbose_name='问题模板')),
            ],
            options={
                'verbose_name': '问卷选项',
                'verbose_name_plural': '问卷选项',
                'ordering': ['question_template', 'option_order', 'id'],
                'unique_together': {('question_template', 'value')},
            },
        ),
    ]
