# Generated by Django 5.2.8 on 2025-12-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_add_recycle_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='base_prices',
            field=models.JSONField(default=dict, help_text='按存储容量存储基础价格，格式：{"128GB": 4500, "256GB": 5200, "512GB": 6500}，单位为元', verbose_name='基础价格表'),
        ),
    ]
