# Generated by Django 5.2.8 on 2025-12-15 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_add_base_prices_to_recycle_device_template'),
        ('secondhand_app', '0023_add_verified_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='battery_capacity',
            field=models.CharField(blank=True, help_text='如：3095mAh', max_length=20, verbose_name='电池容量'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondhand_app.category', verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='charging_type',
            field=models.CharField(blank=True, help_text='如：Lightning、Type-C', max_length=50, verbose_name='充电方式'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='color_options',
            field=models.JSONField(blank=True, default=list, help_text='如：["黑色", "白色", "蓝色"]', verbose_name='颜色选项'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='default_cover_image',
            field=models.CharField(blank=True, max_length=500, verbose_name='默认封面图'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='default_detail_images',
            field=models.JSONField(blank=True, default=list, verbose_name='默认详情图列表'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='description_template',
            field=models.TextField(blank=True, help_text='支持变量：{brand} {model} {storage} {condition} {ram} {version}', verbose_name='商品描述模板'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='ram_options',
            field=models.JSONField(blank=True, default=list, help_text='如：["6GB", "8GB", "12GB"]', verbose_name='运行内存选项'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='screen_size',
            field=models.CharField(blank=True, help_text='如：6.1英寸', max_length=20, verbose_name='屏幕尺寸'),
        ),
        migrations.AddField(
            model_name='recycledevicetemplate',
            name='version_options',
            field=models.JSONField(blank=True, default=list, help_text='如：["国行", "港版", "美版"]', verbose_name='版本选项'),
        ),
    ]
