# Generated by Django 5.2.8 on 2025-12-24 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_remove_template_specs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAuditQueueItem',
        ),
    ]
