from django.urls import path
from .views import (
    LoginView, RefreshTokenView, LogoutView, DashboardMetricsView, StatisticsView,
    InspectionOrdersView, InspectionOrderDetailView, InspectionOrderLogisticsView, InspectionOrderPriceView,
    InspectionOrderPaymentView, InspectionOrderPublishVerifiedView, InspectionOrdersBatchUpdateView,
    RecycledProductsView, VerifiedListingsView, AuditQueueView, UsersView, AuditLogsView, RolesView,
    PaymentOrdersView, PaymentOrderDetailView, PaymentOrderActionView, PaymentOrderSettlementView,
    SettlementSummaryView, VerifiedOrdersAdminView, AuthMeView, ChangePasswordView,
    PermissionsView, MenusView, CategoriesAdminView, ProductsAdminView, UsersFrontendAdminView,
    MessagesAdminView, AddressesAdminView,
    AdminUploadImageView, AdminUploadReportView,
    AdminVerifiedProductListView, AdminVerifiedProductDetailView,
    AdminVerifiedProductPublishView, AdminVerifiedProductUnpublishView,
    # 新增：官方验设备库存
    AdminVerifiedDeviceView, AdminVerifiedDeviceDetailView, AdminVerifiedDeviceListProductView, AdminVerifiedDeviceActionView,
    AdminOfficialInventoryView,
    CreateVerifiedDeviceFromRecycleOrderView,
    # 新增：回收机型模板管理
    RecycleDeviceTemplateView, RecycleQuestionTemplateView, RecycleQuestionOptionView, 
    RecycleTemplateImportView, RecycleTemplateDownloadView
)

urlpatterns = [
    path('auth/login', LoginView.as_view()),
    path('auth/refresh', RefreshTokenView.as_view()),
    path('auth/logout', LogoutView.as_view()),
    path('auth/me', AuthMeView.as_view()),
    path('auth/change-password', ChangePasswordView.as_view()),
    path('permissions', PermissionsView.as_view()),
    path('menus', MenusView.as_view()),
    path('dashboard/metrics', DashboardMetricsView.as_view()),
    path('statistics', StatisticsView.as_view()),
    path('inspection-orders', InspectionOrdersView.as_view()),
    path('inspection-orders/<int:order_id>', InspectionOrderDetailView.as_view()),
    path('inspection-orders/<int:order_id>/status', InspectionOrderDetailView.as_view()),
    path('inspection-orders/<int:order_id>/report', InspectionOrderDetailView.as_view()),
    path('inspection-orders/<int:order_id>/logistics', InspectionOrderLogisticsView.as_view()),
    path('inspection-orders/<int:order_id>/price', InspectionOrderPriceView.as_view()),
    path('inspection-orders/<int:order_id>/received', InspectionOrderLogisticsView.as_view()),
    path('inspection-orders/<int:order_id>/payment', InspectionOrderPaymentView.as_view()),
    path('inspection-orders/<int:order_id>/publish-verified', InspectionOrderPublishVerifiedView.as_view()),
    path('inspection-orders/batch-update', InspectionOrdersBatchUpdateView.as_view()),
    path('recycle-orders/<int:order_id>/create-verified-device/', CreateVerifiedDeviceFromRecycleOrderView.as_view()),
    path('recycled-products', RecycledProductsView.as_view()),
    path('recycled-products/<int:item_id>/publish', RecycledProductsView.as_view()),
    path('recycled-products/<int:item_id>/stock', RecycledProductsView.as_view()),
    # 官方验上传
    path('uploads/images/', AdminUploadImageView.as_view()),
    path('uploads/reports/', AdminUploadReportView.as_view()),
    # 新的官方验商品管理接口（前端使用）
    path('verified-listings/', AdminVerifiedProductListView.as_view()),
    path('verified-listings/<int:pk>/', AdminVerifiedProductDetailView.as_view()),
    path('verified-listings/<int:pk>/publish/', AdminVerifiedProductPublishView.as_view()),
    path('verified-listings/<int:pk>/unpublish/', AdminVerifiedProductUnpublishView.as_view()),
    # 官方验设备（SN级库存）
    path('verified-devices/', AdminVerifiedDeviceView.as_view()),
    path('verified-devices/<int:pk>/', AdminVerifiedDeviceDetailView.as_view()),
    path('verified-devices/<int:pk>/list-product/', AdminVerifiedDeviceListProductView.as_view()),
    path('verified-devices/<int:pk>/<str:action>/', AdminVerifiedDeviceActionView.as_view()),
    path('official-inventory/', AdminOfficialInventoryView.as_view()),
    # 旧的回收产品接口
    path('verified-listings', VerifiedListingsView.as_view()),
    path('verified-listings/<int:item_id>', VerifiedListingsView.as_view()),
    path('verified-listings/<int:item_id>/<str:action>', VerifiedListingsView.as_view()),
    path('audit/queue', AuditQueueView.as_view()),
    path('audit/queue/<int:qid>/decision', AuditQueueView.as_view()),
    path('audit/logs', AuditLogsView.as_view()),
    path('users', UsersView.as_view()),
    path('users/<int:uid>', UsersView.as_view()),
    path('roles', RolesView.as_view()),
    path('payment/orders', PaymentOrdersView.as_view()),
    path('payment/orders/<int:order_id>', PaymentOrderDetailView.as_view()),
    # 将更具体的分账路由置于通配action路由之前，避免被匹配到action视图
    path('payment/order/<int:order_id>/settlement', PaymentOrderSettlementView.as_view()),
    path('payment/order/<int:order_id>/settlement/<str:action>', PaymentOrderSettlementView.as_view()),
    path('payment/order/<int:order_id>/<str:action>', PaymentOrderActionView.as_view()),
    path('payment/settlements/summary', SettlementSummaryView.as_view()),
    path('verified-orders', VerifiedOrdersAdminView.as_view()),
    path('verified-orders/<int:oid>', VerifiedOrdersAdminView.as_view()),
    path('verified-orders/<int:oid>/<str:action>', VerifiedOrdersAdminView.as_view()),
    path('categories', CategoriesAdminView.as_view()),
    path('categories/<int:cid>', CategoriesAdminView.as_view()),
    path('products', ProductsAdminView.as_view()),
    path('products/<int:pid>', ProductsAdminView.as_view()),
    path('products/<int:pid>/<str:action>', ProductsAdminView.as_view()),
    path('frontend-users', UsersFrontendAdminView.as_view()),
    path('frontend-users/<int:uid>', UsersFrontendAdminView.as_view()),
    path('messages', MessagesAdminView.as_view()),
    path('messages/<int:mid>', MessagesAdminView.as_view()),
    path('addresses', AddressesAdminView.as_view()),
    path('addresses/<int:aid>', AddressesAdminView.as_view()),
    # 回收机型模板管理
    path('recycle-templates', RecycleDeviceTemplateView.as_view()),
    path('recycle-templates/<int:template_id>', RecycleDeviceTemplateView.as_view()),
    path('recycle-templates/download-template', RecycleTemplateDownloadView.as_view()),
    path('recycle-templates/import', RecycleTemplateImportView.as_view()),
    path('recycle-templates/<int:template_id>/questions', RecycleQuestionTemplateView.as_view()),
    path('recycle-templates/<int:template_id>/questions/<int:question_id>', RecycleQuestionTemplateView.as_view()),
    path('recycle-templates/<int:template_id>/questions/<int:question_id>/options', RecycleQuestionOptionView.as_view()),
    path('recycle-templates/<int:template_id>/questions/<int:question_id>/options/<int:option_id>', RecycleQuestionOptionView.as_view()),
]
