from django.urls import path
from .views import LoginView, RefreshTokenView, LogoutView, DashboardMetricsView, StatisticsView, InspectionOrdersView, InspectionOrderDetailView, InspectionOrderLogisticsView, InspectionOrderPriceView, InspectionOrderPaymentView, InspectionOrderPublishVerifiedView, InspectionOrdersBatchUpdateView, RecycledProductsView, VerifiedListingsView, AuditQueueView, UsersView, AuditLogsView, RolesView, PaymentOrdersView, PaymentOrderActionView, VerifiedOrdersAdminView, ShopsAdminView, AuthMeView, ChangePasswordView, PermissionsView, MenusView, CategoriesAdminView, ProductsAdminView, UsersFrontendAdminView, MessagesAdminView, AddressesAdminView

urlpatterns = [
    path('auth/login', LoginView.as_view()),
    path('auth/refresh', RefreshTokenView.as_view()),
    path('auth/logout', LogoutView.as_view()),
    path('auth/me', AuthMeView.as_view()),
    path('auth/change-password', ChangePasswordView.as_view()),
    path('permissions', PermissionsView.as_view()),
    path('menus', MenusView.as_view()),
    path('dashboard/metrics', DashboardMetricsView.as_view()),
    path('statistics', StatisticsView.as_view()),
    path('inspection-orders', InspectionOrdersView.as_view()),
    path('inspection-orders/<int:order_id>', InspectionOrderDetailView.as_view()),
    path('inspection-orders/<int:order_id>/status', InspectionOrderDetailView.as_view()),
    path('inspection-orders/<int:order_id>/report', InspectionOrderDetailView.as_view()),
    path('inspection-orders/<int:order_id>/logistics', InspectionOrderLogisticsView.as_view()),
    path('inspection-orders/<int:order_id>/price', InspectionOrderPriceView.as_view()),
    path('inspection-orders/<int:order_id>/payment', InspectionOrderPaymentView.as_view()),
    path('inspection-orders/<int:order_id>/publish-verified', InspectionOrderPublishVerifiedView.as_view()),
    path('inspection-orders/batch-update', InspectionOrdersBatchUpdateView.as_view()),
    path('recycled-products', RecycledProductsView.as_view()),
    path('recycled-products/<int:item_id>/publish', RecycledProductsView.as_view()),
    path('recycled-products/<int:item_id>/stock', RecycledProductsView.as_view()),
    path('verified-listings', VerifiedListingsView.as_view()),
    path('verified-listings/<int:item_id>', VerifiedListingsView.as_view()),
    path('verified-listings/<int:item_id>/<str:action>', VerifiedListingsView.as_view()),
    path('audit/queue', AuditQueueView.as_view()),
    path('audit/queue/<int:qid>/decision', AuditQueueView.as_view()),
    path('audit/logs', AuditLogsView.as_view()),
    path('users', UsersView.as_view()),
    path('users/<int:uid>', UsersView.as_view()),
    path('roles', RolesView.as_view()),
    path('payment/orders', PaymentOrdersView.as_view()),
    path('payment/order/<int:order_id>/<str:action>', PaymentOrderActionView.as_view()),
    path('verified-orders', VerifiedOrdersAdminView.as_view()),
    path('verified-orders/<int:oid>', VerifiedOrdersAdminView.as_view()),
    path('verified-orders/<int:oid>/<str:action>', VerifiedOrdersAdminView.as_view()),
    path('shops', ShopsAdminView.as_view()),
    path('shops/<int:sid>', ShopsAdminView.as_view()),
    path('categories', CategoriesAdminView.as_view()),
    path('categories/<int:cid>', CategoriesAdminView.as_view()),
    path('products', ProductsAdminView.as_view()),
    path('products/<int:pid>', ProductsAdminView.as_view()),
    path('products/<int:pid>/<str:action>', ProductsAdminView.as_view()),
    path('frontend-users', UsersFrontendAdminView.as_view()),
    path('frontend-users/<int:uid>', UsersFrontendAdminView.as_view()),
    path('messages', MessagesAdminView.as_view()),
    path('messages/<int:mid>', MessagesAdminView.as_view()),
    path('addresses', AddressesAdminView.as_view()),
    path('addresses/<int:aid>', AddressesAdminView.as_view()),
]
