# Generated by Django 5.2.8 on 2025-11-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('active', '在售'), ('sold', '已售出'), ('removed', '已下架')], default='active', max_length=20, verbose_name='状态'),
        ),
    ]
