# Generated by Django 5.2.8 on 2025-12-04 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0005_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('model', models.CharField(max_length=100, verbose_name='型号')),
                ('storage', models.CharField(blank=True, max_length=50, verbose_name='存储容量')),
                ('condition', models.CharField(choices=[('new', '全新'), ('like_new', '几乎全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], default='good', max_length=20, verbose_name='成色')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估价格')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最终价格')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加价')),
                ('status', models.CharField(choices=[('pending', '待估价'), ('quoted', '已估价'), ('confirmed', '已确认'), ('shipped', '已寄出'), ('inspected', '已检测'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(verbose_name='收货地址')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '回收订单',
                'verbose_name_plural': '回收订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
