# Generated by Django 5.2.8 on 2025-12-04 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0006_recycleorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品标题')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('condition', models.CharField(choices=[('new', '全新'), ('like_new', '99成新'), ('good', '95成新')], default='good', max_length=20, verbose_name='成色')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '在售'), ('sold', '已售出'), ('removed', '已下架')], default='active', max_length=20, verbose_name='状态')),
                ('location', models.CharField(max_length=100, verbose_name='所在地')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_wechat', models.CharField(blank=True, max_length=50, verbose_name='微信')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('storage', models.CharField(blank=True, max_length=50, verbose_name='存储容量')),
                ('screen_size', models.CharField(blank=True, max_length=20, verbose_name='屏幕尺寸')),
                ('battery_health', models.CharField(blank=True, max_length=20, verbose_name='电池健康度')),
                ('charging_type', models.CharField(blank=True, max_length=50, verbose_name='充电方式')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验货时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_products', to='secondhand_app.category', verbose_name='分类')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_products', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_products_verified', to=settings.AUTH_USER_MODEL, verbose_name='验货人')),
            ],
            options={
                'verbose_name': '官方验货商品',
                'verbose_name_plural': '官方验货商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('shipping_address', models.TextField(verbose_name='收货地址')),
                ('shipping_name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_orders', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='secondhand_app.verifiedproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '官方验货订单',
                'verbose_name_plural': '官方验货订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verified_products/', verbose_name='图片')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='secondhand_app.verifiedproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '官方验货商品图片',
                'verbose_name_plural': '官方验货商品图片',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='secondhand_app.verifiedproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '官方验货收藏',
                'verbose_name_plural': '官方验货收藏',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
