# Generated by Django 5.2.8 on 2025-12-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0007_verifiedproduct_verifiedorder_verifiedproductimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('xy', '易淘'), ('verified', '官方验')], default='xy', max_length=20, verbose_name='分类类型'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'type')},
        ),
    ]
