# Generated by Django 5.2.8 on 2025-12-05 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0008_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, max_length=50, verbose_name='物流承运商'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签收时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='物流单号'),
        ),
        migrations.AddField(
            model_name='verifiedorder',
            name='carrier',
            field=models.CharField(blank=True, max_length=50, verbose_name='物流承运商'),
        ),
        migrations.AddField(
            model_name='verifiedorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签收时间'),
        ),
        migrations.AddField(
            model_name='verifiedorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
        migrations.AddField(
            model_name='verifiedorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='物流单号'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('description', models.TextField(blank=True, verbose_name='店铺描述')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/', verbose_name='店铺Logo')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='店铺地址')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('active', '正常'), ('suspended', '停用'), ('closed', '关闭')], default='active', max_length=20, verbose_name='状态')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='评分')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已认证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='店主')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='secondhand_app.shop', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_products', to='secondhand_app.shop', verbose_name='店铺'),
        ),
    ]
