# Generated by Django 5.2.8 on 2025-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0009_order_carrier_order_delivered_at_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleorder',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='质检时间'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='打款时间'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='payment_account',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='打款账户'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='打款方式'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='payment_note',
            field=models.TextField(blank=True, null=True, verbose_name='打款备注'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', '待打款'), ('paid', '已打款'), ('failed', '打款失败')], default='pending', max_length=20, verbose_name='打款状态'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='price_dispute',
            field=models.BooleanField(default=False, verbose_name='价格异议'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='price_dispute_reason',
            field=models.TextField(blank=True, null=True, verbose_name='价格异议原因'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收到时间'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='拒绝原因'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='寄出时间'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='shipping_carrier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='物流公司'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='运单号'),
        ),
    ]
