# Generated by Django 5.2.8 on 2025-12-06 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0010_recycleorder_inspected_at_recycleorder_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='冻结余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '钱包',
                'verbose_name_plural': '钱包',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', '收入'), ('expense', '支出'), ('withdraw', '提现'), ('refund', '退款')], max_length=20, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易后余额')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('withdraw_status', models.CharField(blank=True, choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败')], max_length=20, null=True, verbose_name='提现状态')),
                ('alipay_account', models.CharField(blank=True, max_length=200, verbose_name='支付宝账号')),
                ('alipay_name', models.CharField(blank=True, max_length=50, verbose_name='支付宝姓名')),
                ('alipay_order_id', models.CharField(blank=True, max_length=100, verbose_name='支付宝订单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondhand_app.recycleorder', verbose_name='关联订单')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='secondhand_app.wallet', verbose_name='钱包')),
            ],
            options={
                'verbose_name': '钱包交易记录',
                'verbose_name_plural': '钱包交易记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
