# Generated by Django 5.2.8 on 2025-12-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0011_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alipay_trade_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='支付宝交易号'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='平台佣金金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_settle_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='卖家分账金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='settle_request_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='分账请求号'),
        ),
        migrations.AddField(
            model_name='order',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分账时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_status',
            field=models.CharField(choices=[('pending', '待分账'), ('settled', '已分账'), ('failed', '分账失败')], default='pending', max_length=20, verbose_name='分账状态'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alipay_login_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='支付宝登录账号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alipay_real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='支付宝姓名'),
        ),
    ]
