# Generated by Django 5.2.8 on 2025-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0012_order_alipay_trade_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alipay_user_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='支付宝用户ID'),
        ),
    ]
