# Generated by Django 5.2.8 on 2025-12-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0013_userprofile_alipay_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='结算方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_order_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='支付宝转账订单号'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_market_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondhand_app.order', verbose_name='关联交易订单'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondhand_app.recycleorder', verbose_name='关联回收订单'),
        ),
    ]
