# Generated by Django 5.2.8 on 2025-12-10 11:29

from django.db import migrations, models
from django.db import connections


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0014_order_settlement_method_order_transfer_order_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE secondhand_app_message
                    ADD COLUMN IF NOT EXISTS message_type VARCHAR(20) NOT NULL DEFAULT 'text'
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE secondhand_app_message
                    ADD COLUMN IF NOT EXISTS payload JSON NULL
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE secondhand_app_message
                    ADD COLUMN IF NOT EXISTS recallable_until DATETIME(6) NULL
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE secondhand_app_message
                    ADD COLUMN IF NOT EXISTS recalled BOOL NOT NULL DEFAULT 0
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='message',
                    name='message_type',
                    field=models.CharField(choices=[('text', '文本'), ('product', '商品'), ('recall', '撤回'), ('system', '系统')], default='text', max_length=20, verbose_name='消息类型'),
                ),
                migrations.AddField(
                    model_name='message',
                    name='payload',
                    field=models.JSONField(blank=True, null=True, verbose_name='扩展数据'),
                ),
                migrations.AddField(
                    model_name='message',
                    name='recallable_until',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='可撤回截止时间'),
                ),
                migrations.AddField(
                    model_name='message',
                    name='recalled',
                    field=models.BooleanField(default=False, verbose_name='是否撤回'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='消息内容'),
        ),
    ]
