# Generated by Django 5.2.8 on 2025-12-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0019_reset_message_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', '文本'), ('product', '商品'), ('image', '图片'), ('recall', '撤回'), ('system', '系统')], default='text', max_length=20, verbose_name='消息类型'),
        ),
    ]
