# Generated by Django 5.2.8 on 2025-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0020_message_image_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedproduct',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500, verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='detail_images',
            field=models.JSONField(default=list, verbose_name='详情图列表'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='质检日期'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='inspection_note',
            field=models.TextField(blank=True, verbose_name='质检说明'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='inspection_reports',
            field=models.JSONField(default=list, verbose_name='质检报告列表'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='inspection_result',
            field=models.CharField(choices=[('pass', '合格'), ('warn', '警告'), ('fail', '不合格')], default='pass', max_length=10, verbose_name='质检结果'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='inspection_staff',
            field=models.CharField(blank=True, max_length=100, verbose_name='质检员'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上架时间'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='removed_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='下架原因'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='verifiedproduct',
            name='condition',
            field=models.CharField(choices=[('new', '全新'), ('like_new', '99成新'), ('good', '95成新'), ('fair', '9成新'), ('poor', '8成新')], default='good', max_length=20, verbose_name='成色'),
        ),
        migrations.AlterField(
            model_name='verifiedproduct',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('active', '在售'), ('sold', '已售出'), ('removed', '已下架'), ('draft', '草稿')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
