# Generated by Django 5.2.8 on 2025-12-14 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0021_verifiedproduct_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleorder',
            name='final_price_confirmed',
            field=models.BooleanField(default=False, verbose_name='最终价已确认'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='payment_retry_count',
            field=models.IntegerField(default=0, verbose_name='打款重试次数'),
        ),
        migrations.AlterField(
            model_name='recycleorder',
            name='status',
            field=models.CharField(choices=[('pending', '待估价'), ('shipped', '已寄出'), ('received', '已收货'), ('inspected', '已检测'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='VerifiedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, unique=True, verbose_name='序列号/ SN')),
                ('imei', models.CharField(blank=True, max_length=100, verbose_name='IMEI/MEID')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('storage', models.CharField(blank=True, max_length=50, verbose_name='存储容量')),
                ('condition', models.CharField(choices=[('new', '全新'), ('like_new', '99成新'), ('good', '95成新'), ('fair', '9成新'), ('poor', '8成新')], default='good', max_length=20, verbose_name='成色')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('repairing', '维修/翻新中'), ('ready', '待上架'), ('listed', '在售'), ('locked', '已锁定'), ('sold', '已售出'), ('removed', '已下架')], default='pending', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='仓位/存放位置')),
                ('barcode', models.CharField(blank=True, max_length=200, verbose_name='条码/二维码内容')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='入库成本')),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='建议售价')),
                ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='封面图')),
                ('detail_images', models.JSONField(default=list, verbose_name='详情图列表')),
                ('inspection_reports', models.JSONField(default=list, verbose_name='质检报告列表')),
                ('inspection_result', models.CharField(choices=[('pass', '合格'), ('warn', '警告'), ('fail', '不合格')], default='pass', max_length=10, verbose_name='质检结果')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='质检日期')),
                ('inspection_staff', models.CharField(blank=True, max_length=100, verbose_name='质检员')),
                ('inspection_note', models.TextField(blank=True, verbose_name='质检说明')),
                ('battery_health', models.CharField(blank=True, max_length=20, verbose_name='电池健康度')),
                ('screen_condition', models.CharField(blank=True, max_length=100, verbose_name='屏幕情况')),
                ('repair_history', models.TextField(blank=True, verbose_name='维修/翻新记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_devices', to='secondhand_app.category', verbose_name='分类')),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='secondhand_app.verifiedproduct', verbose_name='关联商品')),
                ('recycle_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_devices', to='secondhand_app.recycleorder', verbose_name='来源回收单')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_devices', to=settings.AUTH_USER_MODEL, verbose_name='卖家/库存持有人')),
            ],
            options={
                'verbose_name': '官方验库存单品',
                'verbose_name_plural': '官方验库存单品',
                'ordering': ['-created_at'],
            },
        ),
    ]
