# Generated by Django 5.2.8 on 2025-12-15 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_add_template_relations'),
        ('secondhand_app', '0023_add_verified_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieddevice',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='verifieddevice',
            name='ram',
            field=models.CharField(blank=True, max_length=20, verbose_name='运行内存'),
        ),
        migrations.AddField(
            model_name='verifieddevice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_devices', to='admin_api.recycledevicetemplate', verbose_name='机型模板'),
        ),
        migrations.AddField(
            model_name='verifieddevice',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='verifiedproduct',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_products', to='admin_api.recycledevicetemplate', verbose_name='机型模板'),
        ),
    ]
