# Generated by Django 5.2.8 on 2025-12-15 13:50

import django.db.models.deletion
from django.db import migrations, models


def remove_fields_if_exist(apps, schema_editor):
    """Safely remove fields if they exist"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Check which columns exist
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'secondhand_app_verifiedproduct'
            AND COLUMN_NAME IN ('contact_phone', 'contact_wechat', 'location')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Drop only existing columns
        for column in existing_columns:
            cursor.execute(f"ALTER TABLE secondhand_app_verifiedproduct DROP COLUMN {column}")


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_add_template_relations'),
        ('secondhand_app', '0024_add_template_relations'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, migrations.RunPython.noop),
        migrations.AddField(
            model_name='recycleorder',
            name='questionnaire_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='问卷答案'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='选择的颜色'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='selected_ram',
            field=models.CharField(blank=True, max_length=20, verbose_name='选择的运行内存'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='selected_storage',
            field=models.CharField(blank=True, max_length=50, verbose_name='选择的存储容量'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='selected_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='选择的版本'),
        ),
        migrations.AddField(
            model_name='recycleorder',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recycle_orders', to='admin_api.recycledevicetemplate', verbose_name='机型模板'),
        ),
        migrations.AlterField(
            model_name='verifiedproduct',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('active', '在售'), ('sold', '已售出'), ('removed', '已下架'), ('draft', '草稿')], default='active', max_length=20, verbose_name='状态'),
        ),
    ]
