# Generated by Django 5.2.8 on 2025-12-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0025_remove_verifiedproduct_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifiedproduct',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='verifiedproduct',
            name='contact_wechat',
        ),
        migrations.RemoveField(
            model_name='verifiedproduct',
            name='location',
        ),
    ]
