# Generated by Django 5.2.8 on 2025-12-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0026_fix_verified_product_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='contact_phone',
                ),
                migrations.RemoveField(
                    model_name='product',
                    name='contact_wechat',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='verifiedproduct',
                    name='pricing_coefficient',
                    field=models.FloatField(default=1.0, verbose_name='定价系数'),
                ),
                migrations.AddField(
                    model_name='verifiedproduct',
                    name='source_tag',
                    field=models.CharField(blank=True, default='', max_length=50, verbose_name='来源标签'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='recycleorder',
            name='status',
            field=models.CharField(choices=[('pending', '待寄出'), ('shipped', '已寄出'), ('received', '已收货'), ('inspected', '已检测'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
