# Generated by Django 5.2.8 on 2025-12-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0027_remove_product_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='verifiedproduct',
            name='shop',
        ),
    ]
