# Generated by Codex on 2025-12-21
from django.db import migrations


def migrate_recycle_payment_method(apps, schema_editor):
    RecycleOrder = apps.get_model('secondhand_app', 'RecycleOrder')
    qs = RecycleOrder.objects.filter(payment_method='wallet')
    qs.update(payment_method='transfer')
    # Normalize legacy notes mentioning wallet.
    for order in RecycleOrder.objects.filter(payment_note__icontains='??'):
        note = order.payment_note or ''
        note = note.replace('??', '???')
        note = note.replace('???', '?????')
        order.payment_note = note
        order.save(update_fields=['payment_note'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0028_remove_product_shop_remove_verifiedproduct_shop'),
    ]

    operations = [
        migrations.RunPython(migrate_recycle_payment_method, noop_reverse),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
