# Generated by Django 5.2.8 on 2025-12-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0029_remove_wallet_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycleorder',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='recycleorder',
            name='contact_phone',
        ),
    ]
