# Generated by Django 5.2.8 on 2025-12-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0032_verifieddevice_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下架时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='removed_by',
            field=models.CharField(blank=True, max_length=64, verbose_name='下架操作人'),
        ),
        migrations.AddField(
            model_name='product',
            name='removed_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='下架原因'),
        ),
    ]
