# Generated by Django 5.2.8 on 2025-12-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand_app', '0033_product_removed_at_product_removed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[('pending', '待审核'), ('active', '在售'), ('sold', '已售出'), ('removed', '已下架')],
                default='pending',
                max_length=20,
                verbose_name='状态',
            ),
        ),
    ]
